### ISSUE TITLE
Several dead links

### ISSUE THREAD

**Issue by kennyh7279** [dominichayesferen/FerenMoefier#6]
Running the script I was met with a few dead wallpaper links

```
Oops, an error occured downloading a Diary of Our Days at the Breakwater wallpaper! I guess the installer got stuck at this part. That sucks. Aborting now.
Oh no, an error occured downloading the Yoimoi wallpaper. The girls will never reach Antarctica! Aborting now.
Oh no, an Error occured downloading the Wonder Egg Priority wallpaper! Aborting now.
```

Removing these from the script allowed it to complete successfully.  Also i checked the links myself and none of them seem to be loading in the browser either so seems they're dead.

Ran with spoilers on but also checked with non-spoilers and it was the same.

**Comment by dominichayesferen** [comment]
@kennyh7279 Try now using the script in the 'main' branch.

**Comment by kennyh7279** [comment]
Completed just fine no issues.
